#!/usr/bin/env python3

import littlewood
import argparse

import numpy as np
import matplotlib.pyplot as plt

def ensure_roots(degree, coefficients, name="", file=None):
    try:
        return littlewood.io.read(file, name, degree)
    except:
        ...

    roots = np.array([ littlewood.roots(p) for p in littlewood.polynomials(degree, coefficients)])
    try:
        littlewood.io.write(file, name, degree, roots)
    except:
        print("Writing failed :(")
        ...
    return roots


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Generate at plot roots of polynomials.")
    parser.add_argument("--degree", nargs="*", default=[1,6], type=int)
    parser.add_argument("--coefficients", help="", nargs="*", default='littlewood')
    parser.add_argument("--data", help="An h5 file where we can read roots if possible and write roots to.", default=None)

    parser.add_argument("--show", action='store_true')

    args = parser.parse_args()

    options = dict()

    if args.coefficients == 'littlewood':
        options['name'] = 'littlewood'
        options['coefficients'] = littlewood.coefficients.littlewood()
    if args.coefficients[0] == 'roots-of-unity':
        options['coefficients'] = littlewood.coefficients.roots_of_unity(int(args.coefficients[1]))
        options['name'] = 'roots-of-unity-{}'.format(int(args.coefficients[1]))
    if args.coefficients[0] == 'integers':
        options['coefficients'] = littlewood.coefficients.integers(int(args.coefficients[1]))
        options['name'] = 'integers-{}'.format(int(args.coefficients[1]))

    if 1 == len(args.degree):
        options['degrees'] = np.array([args.degree[0]])
    elif 2 == len(args.degree):
        options['degrees'] = np.arange(args.degree[0], args.degree[1]+1)
    elif 3 == len(args.degree):
        options['degrees'] = np.arange(args.degree[0], args.degree[1]+1, args.degree[2])

    options['data'] = args.data

    roots = dict()
    for d in options['degrees']:
        roots[d] = ensure_roots(d, options['coefficients'], name=options['name'], file=options['data'])

    if args.show:
        littlewood.plot.histogram(roots)
        plt.show()
